[tool.poetry]
name = "tessa"
version = "0.1.0"
description = "Find financial assets and get their price history without worrying about different APIs or rate limiting."
authors = ["ymyke"]
license = "MIT"
repository = "https://github.com/ymyke/tessa"
homepage = "https://github.com/ymyke/tessa"
readme = "README.md"
keywords = ["python", "finance", "investing", "financial-analysis", "investment-analysis", "financial-data", "coingecko", "investing-com", "investpy", "pycoingecko"]

[tool.poetry.dependencies]
python = "^3.9"
investpy = "^1.0.8"
frozendict = "^2.3.1"
pycoingecko = "^2.2.0"
pendulum = "^2.1.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
ipykernel = "^6.12.1"
black = "^22.3.0"
pylint = "^2.13.5"
pytest-mock = "^3.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
